- README.md
> Initial draft for the README.md

- data/tokens.json
all tokens are created
label-icon-margin-right is added in figma as gap
> label sizing tokens implemented

- data/tokens.json
Gray-3 fixed and tooltip tokens renamed
> The tooltip tokens are renamed.

- data/tokens.json
the Names are defined according to the new Framework.
Colours could be rethought later - for now, I've kept yellow, teal, purple etc. and tealAccented... because I can't find other semantic names based on current usage.
> New Token Names

- data/tokens.json
Fix some token issues after merging the refactorings
> Sivanov polish tokens

- content/popover.json
This is a test for using another plugin to leverage a content system within Figma
> Popover content

- content/alert.json
- content/dialog.json
- content/hint.json
- content/toast.json
Adding the placeholder files for alerts, dialogs, hints and toasts
> adding component placeholders

- content/alert.json
- content/dialog.json
- content/hint.json
- content/popover.json
- content/toast.json
Adding metadata to appear in the plugin overview to make selection easier
> adding meta

- content/loading messages.json
Adding the placeholder file for data/content loading scenarios
> loading messages content

- data/tokens.json
> Global tokens naming convention

- data/tokens.json
> Component tokens renaming

- data/tokens.json
Cherrypick from Andi's branch as it ran into too many merge issues
> Label and tag tokens

- content/alert.json
- content/dialog.json
- content/hint.json
- content/loading messages.json
- content/popover.json
- content/toast.json
@StefanIvanov LMK your thoughts.
> Autumn content

- data/tokens.json
New components are added: Rating and Notification (panel)
Tokens:
name space: gtmds
component: Rating
category: color
concept: feedback
variant: achieved, in progress
name space: gtmds
component: Notification
category: alert
concept: notification
variant: content-based
> Rating and notification tokens

- data/tokens.json
Adding XXL tokens for the badge avatar
> Badge Avatar size token XXL

- data/tokens.json
After suggestions from Iveto and @kckfm1
> Adding state-related tokens for notifications

- data/tokens.json
> date-picker-token

- data/tokens.json
> link tokens

- data/tokens.json
> time picker tokens

- data/tokens.json
border color
border radius
background fill
Default/Open states
> Accordion tokens 

- data/tokens.json
> Improving the Link Components
